In [10]:
import torch
import torch.nn as nn
import numpy as np

In [12]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [13]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [33]:
from torch.utils.data import TensorDataset, DataLoader
# Import nn.functional
import torch.nn.functional as F

In [15]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [29]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 92.,  87.,  64.],
        [ 87., 134.,  58.],
        [ 74.,  66.,  43.],
        [ 68.,  97.,  70.],
        [ 73.,  67.,  43.]])
tensor([[ 82., 100.],
        [119., 133.],
        [ 57.,  69.],
        [102., 120.],
        [ 56.,  70.]])


In [32]:
model = nn.Linear(3, 2)
list(model.parameters())

[Parameter containing:
 tensor([[-0.1483, -0.2736,  0.5004],
         [ 0.1758,  0.5584, -0.2109]], requires_grad=True),
 Parameter containing:
 tensor([-0.5286,  0.4806], requires_grad=True)]

In [34]:
preds = model(inputs)
preds

tensor([[ -8.1674,  41.6595],
        [ -6.0739,  52.1219],
        [-21.0697,  78.3710],
        [ -8.9023,  34.6212],
        [ -1.9989,  51.4562],
        [ -8.0420,  41.2769],
        [ -5.2999,  51.3526],
        [-20.7176,  78.3359],
        [ -9.0277,  35.0038],
        [ -1.3502,  51.0695],
        [ -7.3934,  40.8902],
        [ -5.9486,  51.7393],
        [-21.8438,  79.1403],
        [ -9.5510,  35.0079],
        [ -2.1242,  51.8388]], grad_fn=<AddmmBackward0>)